default:
    image: docker:24.0.5

stages:          # List of stages for jobs, and their order of execution
  - build

build-job:       # This job runs in the build stage, which runs first.
  stage: build
  script:
    - docker build -t akabot-msg:latest .
  only:
    - "4.0-msg"

build-dev-job:
  stage: build
  script:
    - docker build -t akabot-msg:devel .
  except:
    - "4.0-msg"